In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [7]:
data = pd.read_csv('used_car_dataset.csv')

In [35]:
data.head()
## age, km, transmission, owner, fueltype

,Brand,model,Year,Age,kmDriven,PostedDate,AdditionInfo,AskPrice,Car,Transmission_Manual,Owner_second,FuelType_Hybrid/CNG,FuelType_Petrol
0,Honda,City,2001,23,98000.0,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Honda City,1,1,0,1
1,Toyota,Innova,2009,15,190000.0,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Toyota Innova,1,1,0,0
2,Volkswagen,VentoTest,2010,14,77246.0,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Volkswagen VentoTest,1,0,0,0
3,Maruti Suzuki,Swift,2017,7,83500.0,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Maruti Suzuki Swift,1,1,0,0
4,Maruti Suzuki,Baleno,2019,5,45000.0,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Maruti Suzuki Baleno,0,0,0,1

In [29]:
data = pd.get_dummies(data, columns=['Transmission'], drop_first=True)

In [32]:
data = pd.get_dummies(data, columns=['Owner'], drop_first=True)

In [34]:
data = pd.get_dummies(data, columns=['FuelType'], drop_first=True)

In [18]:
data["kmDriven"] = (
    data["kmDriven"]
    .str.replace(",", "", regex=False)
    .str.replace(" km", "", regex=False)
    .astype(float)
)

## data['Car'] = data['Brand'].astype(str) + ' ' + data['model'].astype(str)

In [9]:
features = ['Age', 'Year', 'kmDriven', 'Transmission_Manual', 'Owner_second', 'FuelType_Hybrid/CNG', 'FuelType_Petrol']

,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,...,Brand_Opel,Brand_Porsche,Brand_Renault,Brand_Rolls-Royce,Brand_Skoda,Brand_Ssangyong,Brand_Tata,Brand_Toyota,Brand_Volkswagen,Brand_Volvo
0,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",...,0,0,0,0,0,0,0,0,0,0
1,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",...,0,0,0,0,0,0,0,1,0,0
2,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",...,0,0,0,0,0,0,0,0,1,0
3,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",...,0,0,0,0,0,0,0,0,0,0
4,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",...,0,0,0,0,0,0,0,0,0,0